#!/usr/bin/bash

print_log () {
    case "$1" in
        E) echo -e "[\x1b[31mERROR\x1b[39m] $2" >&2 ;;
        W) echo -e "[\x1b[33mWARN\x1b[39m] $2" >&2 ;;
        I) echo -e "[\x1b[32mINFO\x1b[39m] $2" >&2 ;;
    esac
}


display_help () {
    case "$1" in
        V) cat <<EOF
   .--.
   |  |
   |  |      Pacoff v0.0.1
  -'  '-     Copyleft (:3) 2026 Speedy1894
  \\    /
   \\  /      This program may be freely distributed
    \\/       however you see fit, I guess -- I can't
.--.  .--.   really stop you.
|   \/   |
'--------'
EOF
#           .-.
#  .--.      \\ \\
# / _.-' .-.  | |   Pacoff v0.0.1
# \\  '-. '-'  | |   Copyleft (:3) 2026-2026 Speedy1894
#  '--'      / /
#           '-'
        ;;
        I) print_log W 'Help message not implemented' ;;
        Q) print_log W 'Help message not implemented' ;;
        R) print_log W 'Help message not implemented' ;;
        S) print_log W 'Help message not implemented' ;;
        *) cat <<EOF
usage:  pacoff <operation> [...]
operations:
    pacoff {-h --help}
    pacoff {-V --version}
    pacoff {-I --install} <options>
    pacoff {-Q --query}   <options> [package(s)]
    pacoff {-R --remove}  [options] <package(s)>
    pacoff {-S --sync}    [options] [pacakge(s)]

use 'pacoff {-h --help}' with an operation for available options
EOF
           ;;
    esac
}


# Test for enhanced getopt, since that's how we parse cmdline args
getopt --test > /dev/null && true
if [[ $? -ne 4 ]]; then
    print_log E '`getopt --test` failed in this environment. This script cannot run.'
    exit 1
fi


LOPERATIONS=help,version,install,query,remove,sync
SOPERATIONS=hVIQRS

PARSEDOPTS=$(getopt --options=$SOPERATIONS --longoptions=$LOPERATIONS --name $(basename "$0") -- "$@") || exit
eval set -- "$PARSEDOPTS"


#TODO: default options need to change based on operation
# Set default options
operationcount=0
operation=''
help=false
dbpath=/var/lib/pacman
cachedir=/var/cache/pacman/pkg
gpgdir=/etc/pacman.d/gnupg
hookdir=/etc/pacman.d/hooks
color=auto
refresh=false
#(this will grow once I get to it)


# Look for operation
while true; do
    case "$1" in
        -V|--version) operation='V'; let operationcount++ ;;
        -I|--install) operation='I'; let operationcount++ ;;
        -Q|--query) operation='Q'; let operationcount++ ;;
        -R|--remove) operation='R'; let operationcount++ ;;
        -S|--sync) operation='S'; let operationcount++ ;;
        -h|--help) help=true ;;
        --) break ;;
        *) ;;
    esac
    shift
done

# Error if the user is asking too much
if [[ $operationcount -gt 1 ]]; then
    print_log E 'only one operation may be used at a time'
    exit 1
fi

# display help message, if applicable
if [[ $help = true ]] || [[ "$operation" = 'V' ]]; then
    display_help $operation
    exit 0
fi

# print hint for uninformed users
if [[ $operationcount -eq 0 ]]; then
    print_log E 'no operation specified (use -h for help)'
    exit 1
fi


# following two lines should be parsed after operation is determined
# LOPTIONS=
# SOPTIONS=


# flow for cmdline arg parsing:
#     - default values for all possible args are laid out
#     - operation is determined (or error thrown if multiple were specified)
#     - separately (depending on operation), other args are determined
