#!/usr/bin/bash

print_log () {
    case "$1" in
        D) [[ -n "$PACOFF_DEBUG" ]] &&
               echo -e "[\x1b[36mDEBUG\x1b[39m] $2" >&2 ;;
        E) echo -e "[\x1b[31mERROR\x1b[39m] $2" >&2 ;;
        W) echo -e "[\x1b[33mWARN\x1b[39m] $2" >&2 ;;
        I) echo -e "[\x1b[32mINFO\x1b[39m] $2" >&2 ;;
    esac
}


display_help () {
    # Start with standalone help messages
    if [[ -z "$1" ]]; then  # Print generic help
        cat <<'EOF'
usage:  pacoff <operation> [...]
operations:
    pacoff {-h --help}
    pacoff {-V --version}
    pacoff {-C --clone}   [options]
    pacoff {-I --install} [options]
    pacoff {-Q --query}   [options] [package(s)]
    pacoff {-R --remove}  [options] <package(s)>
    pacoff {-S --sync}    [options] [pacakge(s)]

use 'pacoff {-h --help}' with an operation for available options
EOF
        return 0
    elif [[ "$1" = 'V' ]]; then  # Print version info
        cat <<'EOF'
   .--.
   |  |
   |  |      Pacoff v0.0.1
  -'  '-     Copyleft (:3) 2026 Speedy1894
  \    /
   \  /      This program may be freely distributed
    \/       however you see fit, I guess -- I can't
.--.  .--.   really stop you.
|   \/   |
'--------'
EOF
#           .-.
#  .--.      \ \
# / _.-' .-.  | |   Pacoff v0.0.1
# \  '-. '-'  | |   Copyleft (:3) 2026-2026 Speedy1894
#  '--'      / /
#           '-'
        return 0
    fi
    
    # Combined help messages w/ shared lines
    case "$1" in
        C) echo 'usage:  pacoff {-C --clone} [options]' ;;
        I) echo 'usage:  pacoff {-I --install} [options]' ;;
        Q) echo 'usage:  pacoff {-Q --query} [options] [package(s)]' ;;
        R) echo 'usage:  pacoff {-R --remove} <options> <package(s)>' ;;
        S) echo 'usage:  pacoff {-S --sync} <options> [package(s)]' ;;
        *) print_log W 'Help message not implemented'; return 1 ;;
    esac
    echo 'options:'
    
    local soptionlist  # All options will be added here, then sorted
    local loptionlist  # same but for options with only long format
    declare -a soptionlist loptionlist
    
    #NOTE: All options should be kept to a maximum of 80 characters (note the leading spaces)
    soptionlist+=('-l, --location <path> set an alternate pacoff directory')
    loptionlist+=('--color <when>   colorize the output')
    
    if [[ "$1" = [CI] ]]; then
        soptionlist+=('-b, --dbpath <path>   set an alternate pacman database location')
        loptionlist+=('--cachedir <dir>  set an alternate pacman package cache location')
        loptionlist+=('--gpgdir <dir>    set an alternate home directory for pacman'\''s GnuPG keys')
    fi
    if [[ "$1" = [RS] ]]; then
        soptionlist+=('-d, --nodeps          skip dependency checks (-dd to skip all checks)')
    fi
    
    # Print options
    IFS=$'\n'
    soptionlist=($(sort <<<"${soptionlist[*]}"))
    loptionlist=($(sort <<<"${loptionlist[*]}"))
    unset IFS
    printf "  %s\n" "${soptionlist[@]}"
    printf "      %s\n" "${loptionlist[@]}"
}
