#!/usr/bin/bash

# Somewhat based on /usr/include/sysexits.h
declare -gr EX_ok=0  # Successful termination
declare -gr EX_misc=1  # Miscellaneous error
declare -gr EX_usage=64  # Incorrect usage in command line
declare -gr EX_noperm=77  # Permission denied
declare -gr EX_notfound=79  # Specified filesystem object doesn't exist
declare -gr EX_exists=80  # Output destination already exists
declare -gr EX_ambiguous=81  # Multiple possibilities exist; must manually specify
declare -gr EX_dependency=82  # A dependency of the script is not present
