#!/usr/bin/env python3

class UsageError(Exception):
    """Inappropriate interaction with the program by the user."""
    __slots__ = ()


class AmbiguityError(Exception):
    """Multiply possibilities exist."""
    __slots__ = ()


# Somewhat based on /usr/include/sysexits.h
def _uncaught_except_hook(exceptiontype:type,
                          value:Exception,
                          traceback:traceback
                          ) -> None:
    if (exceptiontype == KeyboardInterrupt):
        print_log("D", "KeyboardInterrupt")
    elif ("PACOFF_DEBUG" in os.environ):
        print_log("D", "Uncaught exception:", repr(value))
        sys.__excepthook__(exceptiontype, value, traceback)
    
    if (exceptiontype == UsageError): exit(64)
    elif (exceptiontype == PermissionError): exit(77)
    elif (exceptiontype == FileNotFoundError): exit(79)
    elif (exceptiontype == FileExistsError): exit(80)
    elif (exceptiontype == AmbiguityError): exit(81)
    elif (exceptiontype == KeyboardInterrupt): exit(130)
    else: exit(1)


sys.excepthook = _uncaught_except_hook
