#!/usr/bin/bash

# Somewhat based on /usr/include/sysexits.h
declare -rg EX_OK=0  # Successful termination
declare -rg EX_MISC=1  # Miscellaneous error
declare -rg EX_USAGE=64  # Incorrect usage in command line
declare -rg EX_NOPERM=77  # Permission denied
declare -rg EX_NOTFOUND=79  # Specified filesystem object doesn't exist
declare -rg EX_EXISTS=80  # Output destination already exists
declare -rg EX_AMBIGUOUS=81  # Multiple possibilities exist; manually specify
