#!/usr/bin/env python3

# Pacman default locations
LC_pacman:dict = {
    "db":"/var/lib/pacman",
    "cache":"/var/cache/pacman/pkg",
    "keyring":"/etc/pacman.d/gnupg",
    "pacmanlog":"/var/log/pacman.log",
    "pacmanconf":"/etc/pacman.conf",
    "mirrorlist":"/etc/pacman.d/mirrorlist"
}

# Pacoff state dir (relative to dir)
LC_state:dict = {
    "db":"db",
    "cache":"cache",
    "keyring":"gnupg",
    "id":"pacoff-dir",
    "pkglist":"pkglist",
    "pacmanlog":"pacman.log",
    "selflog":"pacoff.log",
    "pacmanconf":"pacman.conf",
    "mirrorlist":"mirrorlist"
}
