#!/usr/bin/bash

# Pacman default locations
declare -gr GL_pacman_db='/var/lib/pacman'
declare -gr GL_pacman_cache='/var/cache/pacman/pkg'
declare -gr GL_pacman_keyring='/etc/pacman.d/gnupg'
declare -gr GL_pacman_pacmanlog='/var/log/pacman.log'
declare -gr GL_pacman_pacmanconf='/etc/pacman.conf'
declare -gr GL_pacman_mirrorlist='/etc/pacman.d/mirrorlist'

# Pacoff state dir
declare -gr GL_state_db='db'
declare -gr GL_state_cache='cache'
declare -gr GL_state_keyring='gnupg'
declare -gr GL_state_id='pacoff-dir'
declare -gr GL_state_pkglist='pkglist'
declare -gr GL_state_pacmanlog='pacman.log'
declare -gr GL_state_selflog='pacoff.log'
declare -gr GL_state_pacmanconf='pacman.conf'
declare -gr GL_state_mirrorlist='mirrorlist'
