#!/usr/bin/env python3

#TODO: implement usage information here (maybe in function for speed unless needed);
#      also, the `type` can be used in the "<argtype>" part of the message

# Types defined in *-cmdlineargs

OP_global_short:dict = {
    "V":"version",
    "C":"clone",
    "F":"files",
    "I":"install",
    "Q":"query",
    "R":"remove",
    "S":"sync",
    "l":"location",
}
OP_global_type:dict = {
    "version":"nil",
    "clone":"nil",
    "files":"nil",
    "install":"nil",
    "query":"nil",
    "remove":"nil",
    "sync":"nil",
    "debug":"cnt",
    "color":"str",
    "location":"str",
}

OP_clone_short:dict = {
    "b":"dbpath",
}
OP_clone_type:dict = {
    "dbpath":"str",
    "cachedir":"str",
    "gpgdir":"str",
}

OP_files_short:dict = {}
OP_files_type:dict = {}

OP_install_short:dict = {
    "b":"dbpath",
}
OP_install_type:dict = {
    "dbpath":"str",
    "cachedir":"str",
    "gpgdir":"str",
}

OP_query_short:dict = {}
OP_query_type:dict = {}

OP_remove_short:dict = {
    "d":"nodeps",
}
OP_remove_type:dict = {
    "nodeps":"cnt",
}

OP_sync_short:dict = {
    "d":"nodeps",
}
OP_sync_type:dict = {
    "nodeps":"cnt",
}
