#!/usr/bin/env python3

def get_state_dir():
    r"""Output the directory which contains the pacoff state.
    
    A pacoff directory is one which contains 'pacoff' in its name and
    contains a file named 'pacoff-dir'. The current directory is
    checked first, followed by all which are children of the current
    working directory. If multiple candidates are found via the second
    method, then none will be selected.
    """
    if (osp.isfile(LC_state["id"])): return "."
    
    result:str = None
    for d in sp.run(("find",
                       ".",
                       "-name","*pacoff*",
                       "-type","d",
                       "-print0"),
                      capture_output=True,
                      text=True).stdout.split("\x00"):
        if (osp.isfile(osp.join(d, LC_state["id"]))):
            if (result is not None): raise AmbiguityError
            result = d
    
    if (result is None): raise FileNotFoundError
    return result
