#!/usr/bin/env python3

def get_cache_list():
    r"""Get a list of packages that *should* be in the pacoff cache.
    
    This uses the `pkglist` file at the root of the pacoff directory, so
    the caller must have already chdired into the pacoff directory.
    
    This function only returns the names of the packages themselves --
    for a true list, the caller must also check for files with '.sig'
    appended.
    """
    wantslist:list = []  # list of wanted packages as obtained from pkglist
    
    with open(LC_state["pkglist"], "rt") as f:
        for line in f.read().split("\n"):
            wantslist.append(line.split(" ")[1])
    
    if (len(wantslist[-1])): wantslist.pop()  # Handle trailing newline
    
    return sp.run(("pacman", "--sync",  #TODO: need to add --root to all pacman commands & use new state structure
                   "--print",
                   "--print-format", "%f",
                   "--", *wantslist),
                  capture_output=True,
                  text=True).stdout.split("\n")
