#!/usr/bin/bash

clone_database () {
    # Copy the pacman database to the pacoff directory.
    #
    # The caller should have already chdir-ed into the pacoff
    # directory. This functon will not clobber any existing files, so
    # those must be removed beforehand.
    #
    # $1 -- Location of the pacman database (e.g., '/var/lib/pacman')
    # $2 -- (bool) Whether 'file' (-F) dbs should be copied
    #
    # ret 1 -- Database already exists
    [[ -e 'db' ]] &&
        return 1
    
    mkdir -- 'db'
    
    cp -R -- "$1/local" 'db/local'
    
    mkdir -- 'db/sync'
    cp -- $(find "$1/sync" -maxdepth 1 -type f -name '*.db') 'db/sync/'
    [[ "$2" = true ]] &&
        cp -- $(find "$1/sync" -maxdepth 1 -type f -name '*.files') 'db/sync/'
    
    return 0
}


clone_keyring () {
    # Copy the pacman GPG keys to the pacoff directory.
    #
    # The caller should have already chdir-ed into the pacoff
    # directory. This functon will not clobber any existing files, so
    # those must be removed beforehand.
    #
    # $1 -- Location of the pacman keyring (e.g., '/etc/pacman.d/gnupg')
    #
    # ret 1 -- Keyring already exists
    [[ -e 'gnupg' ]] &&
        return 1
    
    mkdir -- 'gnupg'
    cp -- $(find "$1" -maxdepth 1 -type f -perm -0444) 'gnupg'
    
    return 0
}
#TODO: create pkglist, copy pacman.conf
