#!/usr/bin/bash

clone_database () {
    # Copy the pacman database to the pacoff directory.
    #
    # The caller should have already chdir-ed into the pacoff
    # directory. This functon will not clobber any existing files, so
    # those must be removed beforehand.
    #
    # $1 -- Location of the pacman database (e.g., '/var/lib/pacman')
    # $2 -- (bool) Whether 'file' (-F) dbs should be copied
    [[ -e 'db' ]] &&
        return $EX_EXISTS
    
    mkdir -- 'db'
    
    cp -R -- "$1/local" 'db/local'
    
    mkdir -- 'db/sync'
    cp -- $(find "$1/sync" -maxdepth 1 -type f -name '*.db') 'db/sync/'
    [[ "$2" = true ]] &&
        cp -- $(find "$1/sync" -maxdepth 1 -type f -name '*.files') 'db/sync/'
    
    return 0
}


clone_keyring () {
    # Copy the pacman GPG keys to the pacoff directory.
    #
    # The caller should have already chdir-ed into the pacoff
    # directory. This functon will not clobber any existing files, so
    # those must be removed beforehand.
    #
    # $1 -- Location of the pacman keyring (e.g., '/etc/pacman.d/gnupg')
    [[ -e 'gnupg' ]] &&
        return $EX_EXISTS
    
    mkdir -- 'gnupg'
    cp -- $(find "$1" -maxdepth 1 -type f -perm -0444) 'gnupg'
    
    return 0
}


clone_operation () {
    # Create a new pacoff directory using pacman's data.
    #
    # $1 -- New directory in which to store pacoff's data
    # $2 -- Location of the pacman database (e.g., '/var/lib/pacman')
    # $3 -- Location of the pacman keyring (e.g., '/etc/pacman.d/gnupg')
    # $4 -- (bool) Whether 'file' (-F) dbs should be copied
    [[ -e "$1" ]] &&
        return $EX_EXISTS
    
    mkdir -- "$1"
    cd -- "$1"
    
    pacoff --version > 'pacoff-dir'
    mkdir -- 'cache'
    touch -- 'pkglist'
    touch -- 'pacman.log'
    cp -- '/etc/pacman.conf' 'pacman.conf'
    
    [[ -f '/etc/pacman.d/mirrorlist' ]] &&
        cp -- '/etc/pacman.d/mirrorlist' 'mirrorlist'
    
    clone_database "$2" "$4"
    clone_keyring "$3"
    
    return 0
}
