#!/usr/bin/bash

clone_operation () {
    # Create a new pacoff directory using pacman's data.
    #
    # $1 -- New directory in which to store pacoff's data
    # $2 -- Location of the pacman database (e.g., '/var/lib/pacman')
    # $3 -- Location of the pacman keyring (e.g., '/etc/pacman.d/gnupg')
    # $4 -- (bool) Whether 'file' (-F) dbs should be copied
    [[ -e "$1" ]] &&
        return $EX_exists
    
    mkdir -p -- "$1"
    cd -- "$1"
    
    # Create miscellaneous files
    pacoff --version > "$LC_state_id"
    mkdir -- "$LC_state_cache"
    touch -- "$LC_state_pkglist"
    touch -- "$LC_state_pacmanlog"
    touch -- "$LC_state_selflog"
    cp -- "$LC_pacman_pacmanconf" "$LC_state_pacmanconf"
    
    [[ -f "$LC_pacman_mirrorlist" ]] &&
        cp -- "$LC_pacman_mirrorlist" "$LC_state_mirrorlist"
    
    # Clone database
    mkdir -- "$LC_state_db"
    cp -R -- "${2}/local" "${LC_state_db}/local"
    
    mkdir -- "${LC_state_db}/sync"
    cp -- $(find "${2}/sync" -maxdepth 1 -type f -name '*.db') "${LC_state_db}/sync/"
    [[ "$4" = true ]] &&
        cp -- $(find "${2}/sync" -maxdepth 1 -type f -name '*.files') "${LC_state_db}/sync/"
    
    # Clone keyring
    mkdir -- "$LC_state_keyring"
    cp -- $(find "$3" -maxdepth 1 -type f -perm -0444) "${LC_state_keyring}/"
    
    return 0
}
