#!/usr/bin/env python3

def clone_operation (dest:str,
                     loc_db:str,
                     loc_keys:str,
                     cp_file_db:bool
                     ) -> None:
    r"""Create a new pacoff directory using pacman's data.
    
    dest:str: New directory in which to store pacoff's data
    loc_db:str: Location of the pacman database ('/var/lib/pacman')
    loc_keys:str: Location of the pacman keyring ('/etc/pacman.d/gnupg')
    cp_file_db:bool: Whether 'file' (-F) dbs should be copied
    """
    if (osp.lexists(dest)): raise FileExistsError
    
    os.makedirs(dest)
    os.chdir(dest)
    
    # Create miscellaneous files
    with open(LC_state["id"], "xt") as f:
        f.write(display_help("V"))  #TODO: give this file useful contents
    os.mkdir(LC_state["cache"])
    open(LC_state["pkglist"], "x").close()
    open(LC_state["pacmanlog"], "x").close()
    open(LC_state["selflog"], "x").close()
    shutil.copyfile(LC_pacman["pacmanconf"], LC_state["pacmanconf"])
    
    if (osp.isfile(LC_pacman["mirrorlist"])):
        shutil.copy(LC_pacman["mirrorlist"], LC_state["mirrorlist"])
    
    # Clone database
    os.mkdir(LC_state["db"])
    shutil.copytree(osp.join(loc_db, "local"), osp.join(LC_state["db"], "local"))
    
    os.mkdir(osp.join(LC_state["db"], "sync"))
    for db in sp.run(("find",
                      osp.join(loc_db, "sync"),
                      "-maxdepth","1",
                      "-type","f",
                      "-name","*.db",
                      "-print0"),
                     capture_output=True,
                     text=True).stdout.split("\x00"):
        shutil.copy(db, osp.join(LC_state["db"], "sync"))
    
    if (cp_file_db):
        for db in sp.run(("find",
                      osp.join(loc_db, "sync"),
                      "-maxdepth","1",
                      "-type","f",
                      "-name","*.files",
                      "-print0"),
                     capture_output=True,
                     text=True).stdout.split("\x00"):
            shutil.copy(db, osp.join(LC_state["db"], "sync"))
    
    # Clone keyring
    os.mkdir(LC_state["keyring"])
    for f in sp.run(("find",
                      loc_keys,
                      "-maxdepth","1",
                      "-type","f",
                      "-perm","-0444",
                      "-print0"),
                     capture_output=True,
                     text=True).stdout.split("\x00"):
        shutil.copy(f, LC_state["keyring"])
