#!/usr/bin/bash

get_cmdline_options () {
    # Return short and long options suitable for a certain operation.
    #
    # The returned options are suitable for `getopt` -- that means a
    # ':' suffix indicates a required argument, and '::' indicates an
    # optional argument. The short options are echoed, followed by a
    # space ( ) and the string of long options.
    #
    # If the parameter equals "-", then all possible options are
    # echoed. If it's empty, then only the universal options are
    # echoed.
    #
    # $1 -- Short version of the operation's flag
    :
}


parse_cmdline_args () {
    # Return an associative array of command-line arguments.
    #
    # This function will use the correct program based on what is
    # present on the user's system and place its output in the given
    # associative array (by nameref). The keys of this array
    # correspond to the long version of each option. For flags, the
    # value will be the number of times it was passed. For options,
    # the value will be the name of an array of all passed values
    # (this is needed in case it was passed multiple times). However,
    # if the option was never given a value by the user, its value in
    # the primary array will be empty and no secondary array will be
    # created.
    #
    # There are two special keys: the hyphen (-) and its double
    # counterpart (--). The values for these keys are the selected
    # operation's short and long name, respectively. If no operation
    # was specified, then these values will be empty.
    #
    # $1 -- The name of the associative array to output to
    # $@ -- Arguments as from the command line
    getopt --test &>/dev/null
    if [[ $? -ne 4 ]]; then
        print_log E '`getopt --test` failed in this environment. This script cannot run.'
        exit $EX_dependency
    fi
    
    declare -n out="$1"  # Associative array for output
    declare -a cmdlineopts=("${@:1}")  # Original command-line options
    out[-]=''
    
    # Separate potential options
    sopts="${ get_cmdline_options '-';}"
    lopts="${sopts#* }"
    sopts="${sopts% *}"
    
    eval set -- "${ getopt --shell=bash --options="$sopts" --longoptions="$lopts" --name='pacoff' -- "${cmdlineopts[@]}";}"
    
    declare -i operationcnt=0
    
    # Look for operation
    for arg in "$@"; do
        case "$arg" in
            -V|--version) [ "${out[-]}" != 'V' ] &&  # Be like pacman
                              operationcnt+=1
                                           out[-]='V' ;;
            -C|--clone)   operationcnt+=1; out[-]='C' ;;
            -F|--files)   operationcnt+=1; out[-]='F' ;;
            -I|--install) operationcnt+=1; out[-]='I' ;;
            -Q|--query)   operationcnt+=1; out[-]='Q' ;;
            -R|--remove)  operationcnt+=1; out[-]='R' ;;
            -S|--sync)    operationcnt+=1; out[-]='S' ;;
            --) break ;;
            *) ;;
        esac
    done
    
    case "${out[-]}" in
        V) out[--]='version' ;;
        C) out[--]='clone' ;;
        F) out[--]='files' ;;
        I) out[--]='install' ;;
        Q) out[--]='query' ;;
        R) out[--]='remove' ;;
        S) out[--]='sync' ;;
        '') out[--]='' ;;
    esac
    
    if [[ $operationcount -gt 1 ]]; then
        print_log E 'only one operation may be used at a time'
        exit $EX_usage
    fi
    
    sopts="${ get_cmdline_options "${out[-]}";}"
    lopts="${sopts#* }"
    sopts="${sopts% *}"
    
    
}
