#!/usr/bin/bash

main () {
    #TODO: need to call parse_cmdline_args() somewhere here
    
    # display help message, if applicable
    if [[ "$help" = true ]] || [[ "$operation" = 'V' ]]; then
        display_help "$operation"
        exit 0
    fi
    
    # print hint for uninformed users
    if [[ $operationcount -eq 0 ]]; then
        print_log E 'no operation specified (use -h for help)'
        exit 1
    fi
}


# Run main() if running as a script
[[ "$(basename "$0")" = 'pacoff' ]] &&
    main "$@"
